COMMANDS = {
    "advancement": "grant|revoke everything|only|from|through|until",
    "anvil": "",
    "asc": "<niveaux>",
    "ascend": "<niveaux>",
    "attribute": "get|base set|get|modifier add|remove|value get",
    "back": "",
    "balm": "dev|export",
    "ban": "<target> [reason]",
    "ban-ip": "<ip|joueur>",
    "banlist": "players|ips",
    "bclib": "place|print|dump_datapack|request_garbage_collection|debug_ore|sliceZ|sliceX",
    "be": "locate_portal|locate_portal_frame|tpnext",
    "bed": "",
    "biomeinfo": "-p|-t",
    "biomelist": "-p <page>",
    "biomels": "-p <page>",
    "bluemap": "[version|help|reload|debug|stop|start|freeze|unfreeze|force-update|fix-edges|update|cancel|purge|worlds|maps|storages]",
    "bossbar": "add|remove|list|get|set",
    "brush": "sphere|cyl|smooth|clipboard|overlay|biome|line|gravity",
    "br": "sphere|cyl|smooth|clipboard|overlay|biome|line|gravity",
    "butcher": "<rayon>|-p|-a|-n|-g|-b|-m|-t|-f",
    "c2me": "notick",
    "ceil": "-f|-g|<degagement>",
    "changedimension": "overworld|nether|end",
    "chunkinfo": "[<args>]",
    "clear": "[cible] [item] [quantité] [nbt]",
    "clearclipboard": "[<args>]",
    "clearhistory": "[<args>]",
    "clone": "<pos1> <pos2> <dest> replace|masked [force|move|normal]",
    "cmdconfig": "",
    "cs": "<fichier> <args>",
    "croptest": "<pos> <block> [destroy|keep|replace]",
    "coro": "config common reload|save|get|set",
    "damage": "<target> <amount> [<damageType>]",
    "data": "get|modify|remove|merge (block|entity|storage)",
    "datapack": "enable|disable|list|priorities",
    "day": "",
    "debug": "start|stop|report",
    "defaultgamemode": "survival|creative|adventure|spectator",
    "deop": "<joueur>",
    "delchunks": "<rayon>>",
    "deltree": "[<args>]",
    "desc": "<niveaux>",
    "descend": "<niveaux>",
    "difficulty": "peaceful|easy|normal|hard",
    "dims": "clone_dimension|remove_dimension",
    "dh": "config|debug|pregen start|status|stop <dimension> <originX> <originZ> <chunkRadius>",
    "effect": "give|clear",
    "enchant": "<cible> <ench> [niveau]",
    "emi": "view|tree",
    "enderchest": "",
    "essentialcommands": "[info|tpa|tpcancel|tpaccept|tpdeny|tpahere|home|overwritehome|back|warp|spawn|nickname|randomteleport|rtp|fly|invuln|workbench|stonecutter|grindstone|anvil|enderchest|wastebin|top|gametime|bed|lastPos|day|rules|feed|heal|extinguish|ext|suicide|night|repair|near|profile|config]",
    "ex": "[<args>]",
    "execute": "run|if|unless|as|at|store|positioned|rotated|facing|align|anchored|in|summon|on",
    "experience": "add|set|query",
    "ext": "extinguish",
    "extinguish": "[<target_player>|<args>]",
    "factoryapi": "display|config",
    "fallingtree": "toggle",
    "farwand": "[<args>]",
    "feed": "[<target_player>]",
    "fill": "<pos1> <pos2> <bloc> [mode]",
    "fixlava": "<rayon>|<profondeur>",
    "fixwater": "<rayon>|<profondeur>",
    "fillbiome": "<pos1> <pos2> <biome> [replace]",
    "fly": "[<flight_enabled>|<target_player>|speed]",
    "flood": "<pattern>|<portee>",
    "floodfill": "<pattern>|<portee>",
    "forceload": "add|remove|query",
    "forestgen": "<taille>|<type>|<densite>",
    "function": "<name>",
    "fwaystones": "delete|forget_all",
    "gamemode": "survival|creative|adventure|spectator [cible]",
    "gamerule": "announceAdvancements|blockExplosionDropDecay|commandBlockOutput|commandModificationBlockLimit|disableElytraMovementCheck|disableRaids|doDaylightCycle|doEntityDrops|doFireTick|doImmediateRespawn|doInsomnia|doLimitedCrafting|doMobLoot|doMobSpawning|doPatrolSpawning|doTileDrops|doTraderSpawning|doVinesSpread|doWardenSpawning|doWeatherCycle|drowningDamage|fallDamage|fireDamage|forgiveDeadPlayers|freezeDamage|globalSoundEvents|keepInventory|lavaSourceConversion|logAdminCommands|maxCommandChainLength|maxEntityCramming|mobExplosionDropDecay|mobGriefing|naturalRegeneration|playersSleepingPercentage|randomTickSpeed|reducedDebugInfo|sendCommandFeedback|showDeathMessages|snowAccumulationHeight|spawnRadius|spectatorsGenerateChunks|tntExplosionDropDecay|universalAnger|waterSourceConversion True|False",
    "give": "<cible> <item> [quantité] [nbt/components]",
    "gmask": "<masque>",
    "grindstone": "",
    "heal": "[<target_player>]",
    "help": "[commande]",
    "home": "tp|tp_other|tp_offline|set|delete|list|list_offline",
    "horde": "trigger",
    "ignore": "<player>",
    "info": "[<args>]",
    "io": "report|config",
    "invuln": "[<target_player>]",
    "item": "replace|modify|display",
    "jade": "show|hide",
    "j": "[<args>]",
    "jfr": "start|stop|dump",
    "jumpto": "[<args>]",
    "l": "-b|-i|<texte>|-p <page>",
    "kick": "<joueur> [raison]",
    "kill": "<cible>",
    "lastPos": "<target_player>",
    "list": "[uuids]",
    "listchunks": "[<args>]",
    "livingthings": "github|issue|wiki|discord|curseforge|modrinth",
    "locate": "structure|biome|poi",
    "loot": "give|insert|replace|spawn",
    "lrbuild": "[<args>]",
    "mask": "<masque>",
    "m": "<player> <message>",
    "material": "<pattern>",
    "me": "<action>",
    "mclogs": "list|share",
    "midnightconfig": "the_bumblezone|dynamiclights|ubesdelight",
    "mobcaps": "",
    "modernfix": "upgradeStructures|mcfunctions",
    "msg": "<cible> <message>",
    "navwand": "[<args>]",
    "near": "[<range>]",
    "nickname": "set|clear|reveal",
    "night": "",
    "none": "[<args>]",
    "observable": "[config|run|allow|deny|set|tp|reset]",
    "op": "<joueur>",
    "pardon": "<joueur>",
    "pardon-ip": "<ip>",
    "particle": "<particule> [pos] [delta] [speed] [count] [force|normal] [cible]",
    "perf": "start|stop",
    "pickaxe": "[<args>]",
    "place": "feature|jigsaw|structure|template",
    "playsound": "<son> <source> <cible> [pos] [vol] [pitch] [minVol]",
    "publish": "[port]",
    "randomteleport": "",
    "range": "<distance>",
    "r": "<message>",
    "recipe": "give|take <cible> <recette|*>",
    "repl": "[<args>]",
    "reply": "<message>",
    "repair": "[<target_player>]",
    "replace": "<masque> <pattern>",
    "replacenear": "<rayon> <masque> <pattern>",
    "reload": "recharge datapacks",
    "respawn": "",
    "restore": "<snapshot>",
    "return": "<value>",
    "ride": "mount|dismount|start_riding|stop_riding|summon_rider",
    "rtp": "",
    "rules": "[reload]",
    "save-all": "[flush]",
    "save-off": "désactive autosave",
    "save-on": "réactive autosave",
    "scale": "<operation>|randomize|get|compute|reset|modifier|delay|easing|persist|nbt|debug",
    "say": "<message>",
    "schem": "list|formats|load|save|delete|share",
    "schematic": "list|formats|load|save|delete|share",
    "schedule": "function|clear",
    "scoreboard": "objectives|players",
    "sc": "servercore",
    "searchitem": "-b|-i|<texte>|-p <page>",
    "seed": "affiche graine",
    "selwand": "[<args>]",
    "servercore": "reload|settings|status",
    "setblock": "<pos> <bloc> [mode]",
    "setidletimeout": "<minutes>",
    "setworldspawn": "[<pos>]",
    "size": "[<args>]",
    "snap": "[<args>]",
    "snapshot": "[<args>]",
    "snow": "<profondeur>",
    "spawn": "[set|tp]",
    "spawnpoint": "[cible] [pos] [angle]",
    "spectate": "[<target>]",
    "sp": "[<args>]",
    "spreadplayers": "<center> <spreadDistance> <maxRange> (<respectTeams>|under)",
    "stats": "edit|clear|query",
    "stonecutter": "",
    "stop": "arrête le serveur",
    "stopsound": "<targets> [*|master|music|record|weather|block|hostile|neutral|player|ambient|voice]",
    "structure": "save|load|delete|list",
    "styledchat": "[reload|set|get|clear]",
    "summon": "<entité> [pos] [nbt/components]",
    "suicide": "",
    "t": "<player> <message>",
    "tag": "<cible> add|remove|list",
    "tb": "access|remove|clear|restore|unpack",
    "team": "add|remove|empty|join|leave|list|modify",
    "teammsg": "<message>",
    "teleport": "<location>|<destination>|<cible>",
    "tell": "<player> <message>",
    "tellform": "<targets> <message>",
    "tellraw": "<cible> <json>",
    "time": "set|add|query",
    "title": "<cible> title|subtitle|actionbar|times|clear|reset",
    "thaw": "[<args>]",
    "thru": "[<args>]",
    "toggleeditwand": "[<args>]",
    "toggleplace": "[<args>]",
    "tool": "info|repl <pattern>|lrbuild <gauche> <droite>|deltree|floodfill <pattern>",
    "top": "",
    "tp": "<cible> <dest|pos [rot]>",
    "tpaccept": "[<target_player>]",
    "tpahere": "<target_player>",
    "tpa": "<target_player>",
    "tpcancel": "",
    "tpdeny": "[<target_player>]",
    "tracemask": "<masque>",
    "tree": "<type>",
    "trigger": "<objectif> [add|set]",
    "trinkets": "set <group> <slot> <offset> <stack> [<count>]",
    "unloadedactivity": "config|benchmark",
    "undo": "[<args>]",
    "unstuck": "[<args>]",
    "up": "<distance>|-f|-g",
    "view": "inv|echest|trinket",
    "villagername": "toggle|add|remove|set|info",
    "w": "<player> <message>",
    "warp": "existing|id|<text>|tp|tp_other|set|delete|list",
    "wastebin": "",
    "waterframes": "edit|audit|give|whitelist",
    "weather": "clear|rain|thunder [durée]",
    "we": "help|version|reload|perf",
    "whitelist": "on|off|add|remove|list|reload",
    "worldborder": "set|add|center|damage|warning",
    "worldedit": "help|version|reload|perf",
    "xp": "experience",
    "//": "super-pickaxe <single|area|recursive>",
    "//br": "voir //brush.",
    "//brush": "pinceau : sphere <pattern> <rayon> | smooth <rayon> [itérations] | clipboard [-a] [rayon] | cyl <pattern> <rayon> [hauteur] | biome <biome> <rayon> …",
    "//calc": "<expression mathématique>",
    "//calculate": "<expression mathématique>.",
    "//center": "<pattern> — place le(s) bloc(s) au centre de la sélection",
    "//chunk": "sélectionne le chunk courant (16×16×hauteur)",
    "//clearhistory": "sans argument — vide undo/redo",
    "//contract": "<distance> [distanceOpposée] [direction|<axe>]",
    "//copy": "[-a] [-e] [-b] [-s] — copie la sélection",
    "//count": "<masque> — compte les blocs correspondant",
    "//curve": "<pattern> [épaisseur] — courbe entre points de la sélection",
    "//cut": "[-a] [-e] [-b] — coupe la sélection vers le presse-papiers",
    "//cyl": "<pattern> <rayon[,rayonY]> [hauteur]",
    "//deform": "[-cor] <exprX> <exprY> <exprZ> — déforme la sélection par expressions",
    "//desel": "sans argument — désélectionne",
    "//deselect": "sans argument — désélectionne",
    "//distr": "[masque] [-c|-d] — distribution des blocs dans la sélection",
    "//drain": "<rayon> — vide eau/lave au point de placement",
    "//drawsel": "[on|off] — affiche les contours de sélection côté client",
    "//eval": "<expression>",
    "//evaluate": "<expression>",
    "//ex": "<rayon> — éteint les feux (alias d’extinguish)",
    "//expand": "<distance> [distanceOpposée] [direction|<axe>]",
    "//ext": "<rayon> — éteint les feux (alias d’extinguish)",
    "//extinguish": "<rayon> — éteint les feux",
    "//faces": "<pattern> — remplit les faces de la boîte englobante (alias //outline)",
    "//fast": "[on|off]",
    "//fill": "<pattern> <rayon> [profondeur] — comble un trou vers le bas",
    "//fillr": "<pattern> <rayon> [profondeur] — comble récursif (cavités)",
    "//flora": "sans argument — place de la flore aléatoire dans la sélection",
    "//forest": "[type] [densité] — génère une forêt dans la sélection",
    "//gb": "[-chor] <biome> <expression> — alias de //generatebiome",
    "//g": "[-chor] <pattern> <expression> — alias de //generate",
    "//gen": "[-chor] <pattern> <expression> — alias de //generate",
    "//genbiome": "[-chor] <biome> <expression>",
    "//generate": "[-chor] <pattern> <expression>",
    "//generatebiome": "[-chor] <biome> <expression>",
    "//green": "<rayon> — ‘verdit’ la zone (herbe, feuilles)",
    "//gmask": "[masque] — masque global appliqué à tous les edits",
    "//hcyl": "<pattern> <rayon[,rayonY]> [hauteur] — cylindre creux",
    "//hollow": "[épaisseur] — évidage de la sélection",
    "//hpyramid": "<pattern> <taille> — pyramide creuse",
    "//hpos1": "sans argument — pos1 sur le bloc visé",
    "//hpos2": "sans argument — pos2 sur le bloc visé",
    "//hsphere": "<pattern> <rayon[,ry,rz]> [raised]",
    "//inset": "<distance> [direction] — réduit la sélection",
    "//l": "<requête…> [-b|-i] [-p <page>] — alias de //searchitem",
    "//line": "<pattern> [épaisseur] — ligne entre pos1 et pos2",
    "//limit": "[nombre] — limite de blocs par opération",
    "//lrbuild": "<bloc_clic_gauche> <bloc_clic_droit> — outil build à distance",
    "//material": "<pattern> — définit le matériau du pinceau courant",
    "//middle": "<pattern> — alias de //center",
    "//move": "<distance> [direction] [pattern_remplissage] [-a]",
    "//naturalize": "sans argument — couche sol naturelle (herbe/terre/pierre)",
    "//navwand": "sans argument — donne la baguette de navigation",
    "//outset": "<distance> [direction] — étend la sélection vers l’extérieur",
    "//overlay": "<pattern> — applique une couche au dessus du terrain",
    "//paste": "[-a] [-e] [-b] [-o] [-s] — colle depuis le presse-papiers",
    "//perf": "[on|off|list] — paramètres de performance WorldEdit",
    "//pos1": "[x y z] — fixe pos1",
    "//pos2": "[x y z] — fixe pos2",
    "//pyramid": "<pattern> <taille>",
    "//re": "[étapes] — alias de //redo",
    "//redo": "[étapes] — refait l’historique",
    "//regen": "sans argument — régénère la sélection depuis la seed du monde",
    "//removenear": "<bloc> <rayon> — supprime les blocs donnés près du joueur",
    "//removebelow": "[taille] [hauteur] — supprime sous le joueur/la sélection",
    "//replace": "[masque] <pattern> — remplace dans la sélection",
    "//replacenear": "<rayon> <masque> <pattern> — remplace près du joueur",
    "//restore": "[snapshot] — restaure depuis un snapshot configuré",
    "//rotate": "<x> [y] [z] — rotation du presse-papiers en degrés",
    "//schem": "<list|formats|load|save|delete|share>",
    "//schematic": "<list|formats|load|save|delete|share>",
    "//search": "<requête…> [-b|-i] [-p <page>] — alias de //searchitem",
    "//searchitem": "<requête…> [-b|-i] [-p <page>]",
    "//sel": "[cuboid|extend|poly|ellipsoid|sphere|cyl|convex] [-d]",
    "//selwand": "sans argument — donne la baguette de sélection",
    "//shift": "<distance> [direction] — décale la sélection",
    "//size": "sans argument — infos de sélection",
    "//smooth": "[rayon] [itérations] — lisse le terrain sélectionné",
    "//snow": "<taille> [hauteur] — ajoute neige/gèle l’eau",
    "//sphere": "<pattern> <rayon[,ry,rz]> [raised]",
    "//stack": "<compte> [direction] — répète la sélection",
    "//thaw": "<taille> [hauteur] — enlève neige/dégèle glace",
    "//timeout": "[secondes] — fixe le délai de calcul",
    "//toggleplace": "sans argument — bascule position de placement (joueur/pos1)",
    "//undo": "[étapes] — annule l’historique",
    "//walls": "<pattern> — construit les murs de la sélection",
    "//wand": "[-n] — donne la hache de sélection",
    "//watchdog": "[hookMode] — ajuste l’intégration watchdog serveur",
    "//world": "[nom_du_monde] — force le monde ciblé par WE",
    ";": "Préfixe des commandes WorldEdit Bedrock (;set, ;line…)",
}

STRUCTURES = {
    "betterdeserttemples": ["applies_mining_fatigue", "better_desert_temples", "desert_temple"],
    "betterdungeons": [
        "better_dungeons",
        "skeleton_dungeon",
        "small_dungeon",
        "small_nether_dungeon",
        "spider_dungeon",
        "zombie_dungeon",
    ],
    "betterend": [
        "end_village",
        "eternal_portal",
        "giant_ice_star",
        "giant_mossy_glowshroom",
        "megalake",
        "megalake_small",
        "mountain",
        "painted_mountain",
    ],
    "betterfortresses": ["better_fortresses"],
    "betterjungletemples": ["better_jungle_temples", "jungle_temple"],
    "bettermineshafts": [
        "better_mineshafts",
        "mineshaft_acacia",
        "mineshaft_desert",
        "mineshaft_dripstone",
        "mineshaft_ice",
        "mineshaft_jungle",
        "mineshaft_lush",
        "mineshaft_mesa",
        "mineshaft_mushroom",
        "mineshaft_oak",
        "mineshaft_overgrown",
        "mineshaft_red_desert",
        "mineshaft_spruce",
        "mineshaft_spruce_snowy",
    ],
    "betteroceanmonuments": ["better_ocean_monuments", "ocean_monument"],
    "betterwitchhuts": ["witch_circle", "witch_hut"],
    "deeper_dark": ["amethyst_mines_decoration", "ancient_fortress", "amethyst_mineshaft", "sculk_trap"],
    "explorify": [
        "badlands_pyramid",
        "black_spiral",
        "campsite",
        "dark_forest_settlement",
        "desert_shrine",
        "end_shipwreck",
        "farmstead",
        "guide_post_cold",
        "guide_post_warm",
        "mangrove_hut",
        "mausoleum",
        "ruins",
        "supply_cache/birch",
        "supply_cache/dark",
        "supply_cache/desert",
        "supply_cache/forest",
        "supply_cache/jungle",
        "supply_cache/mangrove",
        "supply_cache:taiga",
        "tavern",
        "watchtower/plains",
        "watchtower/savanna",
        "watchtower/taiga",
    ],
    "graveyard": [
        "altar",
        "crypt",
        "dead_tree",
        "giant_mushroom",
        "haunted_house",
        "large_graveyard",
        "lich_prison",
        "medium_graveyard",
        "memorial_tree",
        "mushroom_grave",
        "ruins",
        "small_desert_grave",
        "small_desert_graveyard",
        "small_grave",
        "small_graveyard",
        "small_mountain_grave",
        "small_savanna_grave",
    ],
    "hopo": [
        "underwater/underwater_city",
        "underwater/underwater_fossils",
        "underwater/underwater_small_ruins",
        "underwater/underwater_warm_small_ruins",
        "underwaterstructure",
    ],
    "illagerinvasion": ["firecaller_hut", "illager_fort", "illusioner_tower", "labyrinth", "sorcerer_hut"],
    "incendium": [
        "abandoned_tower",
        "forbidden_castle",
        "infernal_altar",
        "nether_reactor",
        "piglin_village",
        "pipeline",
        "quartz_kitchen",
        "ruined_lab",
        "sanctum",
    ],
    "limbo": [
        "big",
        "camp",
        "camp_old",
        "cogs",
        "concept",
        "fort",
        "grass",
        "hut",
        "hut_new",
        "mushroom_big",
        "mushroom_giga",
        "mushroom_pointy",
        "mushroom_regular",
        "mushroom_square",
        "mushroom_weird",
        "oasis",
        "portal",
        "spider",
        "well",
    ],
    "minecraft": [
        "ancient_city",
        "bastion_remnant",
        "buried_treasure",
        "cats_spawn_as_black",
        "cats_spawn_in",
        "desert_pyramid",
        "dolphin_located",
        "end_city",
        "eye_of_ender_located",
        "fortress",
        "igloo",
        "jungle_pyramid",
        "mansion",
        "mineshaft",
        "mineshaft_mesa",
        "monument",
        "nether_fossil",
        "ocean_ruin",
        "ocean_ruin_cold",
        "ocean_ruin_warm",
        "on_ocean_explorer_maps",
        "on_treasure_maps",
        "on_woodland_explorer_maps",
        "pillager_outpost",
        "ruined_portal",
        "ruined_portal_desert",
        "ruined_portal_jungle",
        "ruined_portal_mountain",
        "ruined_portal_nether",
        "ruined_portal_ocean",
        "ruined_portal_swamp",
        "shipwreck",
        "shipwreck_beached",
        "stronghold",
        "swamp_hut",
        "trail_ruins",
        "village",
        "village_desert",
        "village_plains",
        "village_savanna",
        "village_snowy",
        "village_taiga",
    ],
    "mns": [
        "circle_blackstone",
        "circle_nether_brick",
        "grave_yard",
        "large_blackstone_pillars",
        "large_blackstone_walls",
        "large_nether_brick",
        "lava_pool",
        "medium_blackstone",
        "medium_crimson_fungus",
        "medium_crimson_fungus_2",
        "medium_crimson_well",
        "medium_house",
        "medium_house_2",
        "medium_warped_fungus",
        "medium_warped_fungus_2",
        "medium_warped_well",
        "small_nether_brick",
        "smoking_shrine",
        "very_small_blackstone",
        "very_small_blackstone_2",
        "very_small_blackstone_3",
        "very_small_blackstone_4",
        "very_small_nether_brick",
        "very_small_nether_brick_2",
        "very_small_nether_brick_3",
        "warped_pool",
    ],
    "morevillagers": [
        "on_fortress_explorer_maps",
        "on_jungle_temple_explorer_maps",
        "on_mineshaft_explorer_maps",
        "on_swamp_hut_explorer_maps",
    ],
    "nova_structures": [
        "badlands_miner_outpost",
        "bunker",
        "conduit_ruin",
        "creeping_crypt",
        "desert_ruins",
        "donjon",
        "firewatch_tower",
        "firewatch_tower_birch",
        "firewatch_tower_cherry",
        "firewatch_tower_dark_oak",
        "firewatch_tower_forest",
        "firewatch_tower_jungle",
        "firewatch_tower_mangrove",
        "firewatch_tower_savanna",
        "firewatch_tower_swamp",
        "firewatch_tower_taiga",
        "hamlet",
        "illager_camp",
        "illager_hideout",
        "illager_manor",
        "jungle_ruins",
        "mangrove_witch_hut",
        "nether_keep",
        "nether_port",
        "nether_skeleton_tower_basalt",
        "nether_skeleton_tower_crimson",
        "nether_skeleton_tower_soul",
        "nether_skeleton_tower_warped",
        "piglin_camp",
        "piglin_outstation",
        "ruin_town",
        "skeleton_camp_crimson",
        "skeleton_camp_soul",
        "skeleton_camp_warped",
        "skeleton_camp_waste",
        "stray_fort",
        "tavern_acacia",
        "tavern_birch",
        "tavern_cherry",
        "tavern_dark_oak",
        "tavern_desert",
        "tavern_jungle",
        "tavern_mangrove",
        "tavern_oak",
        "tavern_snowy",
        "tavern_spruce",
        "tavern_swamp",
        "undead_crypt",
        "underground_house",
        "village_jungle",
        "village_swamp",
        "well_birch",
        "well_dark_oak",
        "well_jungle",
        "well_oak",
        "well_savana",
        "well_spruce",
        "wich_villa",
        "wild_ruin",
    ],
    "nullscape": ["dragon_skeleton"],
    "the_bumblezone": [
        "ancient_hoops",
        "ancient_shrine",
        "battle_cubes",
        "bee_house",
        "bee_queen_mining_fatigue",
        "bumbling_beepartments",
        "candle_parkour",
        "cannon_range",
        "cell_maze",
        "cherry_veteran_tree",
        "dance_floor",
        "essence/knowing/prevent_displaying_name",
        "explorer_map/pirate_locating",
        "gazebuzz_cluster",
        "goliath_honey_fountain",
        "hanging_garden",
        "hive_temple",
        "honey_cave_room",
        "honey_compass/default_locating",
        "honey_compass/lesser_misc_locating",
        "honey_compass/misc_locating",
        "honey_compass/sempiternal_sanctums/blue",
        "honey_compass/sempiternal_sanctums/green",
        "honey_compass/sempiternal_sanctums/purple",
        "honey_compass/sempiternal_sanctums/red",
        "honey_compass/sempiternal_sanctums/white",
        "honey_compass/sempiternal_sanctums/yellow",
        "honey_compass/throne_locating",
        "honey_fountain",
        "honey_slime_ranch",
        "honitel",
        "ice_monolith",
        "mite_fortress",
        "no_caves",
        "no_dungeons",
        "no_floaters_piecewise",
        "no_giant_spikes",
        "no_hive_voyager_piecewise",
        "no_honeycomb_holes",
        "no_honeycomb_holes_piecewise",
        "overgrown_flower",
        "phantasm_aviary",
        "pirate_ship",
        "pollinated_stream",
        "sempiternal_sanctum_blue",
        "sempiternal_sanctum_green",
        "sempiternal_sanctum_purple",
        "sempiternal_sanctum_red",
        "sempiternal_sanctum_white",
        "sempiternal_sanctum_yellow",
        "sempiternal_sanctums",
        "stinger_spear_shrine",
        "subway",
        "throne_pillar",
        "wrath_causing",
    ],
    "towns_and_towers": [
        "exclusives/pillager_outpost_classic",
        "exclusives/pillager_outpost_iberian",
        "exclusives/pillager_outpost_mediterranean",
        "exclusives/pillager_outpost_oriental",
        "exclusives/pillager_outpost_rustic",
        "exclusives/pillager_outpost_swedish",
        "exclusives/pillager_outpost_tudor",
        "exclusives/village_classic",
        "exclusives/village_iberian",
        "exclusives/village_mediterranean",
        "exclusives/village_nilotic",
        "exclusives/village_piglin",
        "exclusives/village_rustic",
        "exclusives/village_swedish",
        "exclusives/village_tudor",
        "exclusives/village_wandering_trader_camp",
        "mimic_desert",
        "pillager_outpost_badlands",
        "pillager_outpost_beach",
        "pillager_outpost_birch_forest",
        "pillager_outpost_desert",
        "pillager_outpost_flower_forest",
        "pillager_outpost_forest",
        "pillager_outpost_grove",
        "pillager_outpost_jungle",
        "pillager_outpost_meadow",
        "pillager_outpost_mushroom_fields",
        "pillager_outpost_ocean",
        "pillager_outpost_old_growth_taiga",
        "pillager_outpost_savanna",
        "pillager_outpost_savanna_plateau",
        "pillager_outpost_snowy_beach",
        "pillager_outpost_snowy_plains",
        "pillager_outpost_snowy_slopes",
        "pillager_outpost_snowy_taiga",
        "pillager_outpost_sparse_jungle",
        "pillager_outpost_sunflower_plains",
        "pillager_outpost_swamp",
        "pillager_outpost_taiga",
        "pillager_outpost_wooded_badlands",
        "town",
        "village_badlands",
        "village_beach",
        "village_birch_forest",
        "village_flower_forest",
        "village_forest",
        "village_grove",
        "village_jungle",
        "village_meadow",
        "village_mushroom_fields",
        "village_ocean",
        "village_old_growth_taiga",
        "village_savanna_plateau",
        "village_snowy_slopes",
        "village_snowy_taiga",
        "village_sparse_jungle",
        "village_sunflower_plains",
        "village_swamp",
        "village_wooded_badlands",
        "wreckage_ocean",
    ],
}


def flat_commands():
    return list(COMMANDS.keys())


def suggest_commands(prefix):
    if not prefix:
        return []
    p = prefix.strip()
    if p.startswith("/"):
        p = p[1:]
    keys = sorted(COMMANDS.keys())
    res = [k for k in keys if k.startswith(p)]
    return res if res else [k for k in keys if p in k]
